<?php

namespace ContainerH1J1v2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T2EvGW0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T2EvGW0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T2EvGW0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'atelier' => ['privates', '.errored..service_locator.T2EvGW0.App\\Entity\\Atelier', NULL, 'Cannot autowire service ".service_locator.T2EvGW0": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'atelier' => 'App\\Entity\\Atelier',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
