<?php

namespace ContainerH1J1v2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SfxZffIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SfxZffI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SfxZffI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'atelier' => ['privates', '.errored..service_locator.SfxZffI.App\\Entity\\Atelier', NULL, 'Cannot autowire service ".service_locator.SfxZffI": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".'],
            'atelierRepository' => ['privates', 'App\\Repository\\AtelierRepository', 'getAtelierRepositoryService', true],
            'markdownAtelier' => ['privates', 'App\\MesServices\\MarkdownAtelier', 'getMarkdownAtelierService', true],
        ], [
            'atelier' => 'App\\Entity\\Atelier',
            'atelierRepository' => 'App\\Repository\\AtelierRepository',
            'markdownAtelier' => 'App\\MesServices\\MarkdownAtelier',
        ]);
    }
}
