<?php

namespace ContainerH1J1v2M;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAtelier4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T2EvGW0.App\Entity\Atelier' shared service.
     *
     * @return \App\Entity\Atelier
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T2EvGW0": it needs an instance of "App\\Entity\\Atelier" but this type has been excluded in "config/services.yaml".');
    }
}
